UnitTests/OIDAuthStateTests.m

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/27)

Fixes capitalization typos in test method names.

---

Source/OIDAuthState.m

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/44)

isAuthorized now returns YES if a refresh_token is available.

---

AppAuth.podspec
Example-Mac/Source/AppAuthExampleViewController.m
Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.h
Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.m

Added Treat Warnings as Errors flag to podspec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/52)

Fixed compiler warnings in OIDLoopbackHTTPServer.

---

Source/OIDURLQueryComponent.m
UnitTests/OIDURLQueryComponentTests.m

Fixes #48
– OIDURLQueryComponent.URLEncodedParameters now percent-encodes the parameters on iOS 8+ as it was meant to.
– OIDURLQueryComponent.URLByReplacingQueryInURL always uses OIDURLQueryComponent.URLEncodedParameters for consistency.
– Corrects ambiguity of the '+' character in URLs caused by `application/x-www-form-urlencoded` by always percent-encoding it.
– Added a URL encoding test based on the encoding sample data provided by RFC6749 Appendix B.
– Added more reserved characters to existing tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/54)

Fixes URL encoding issues.

---

Source/OIDAuthorizationService.m

– Fixes #56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/59)

Correctly returns access_denied error when the user declines.

---

Source/OIDAuthorizationRequest.h
Source/OIDAuthorizationService.m
Source/OIDURLQueryComponent.m

Relaxes some conditions to prepare for https://tools.ietf.org/html/draft-ietf-oauth-device-flow support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/66)

Some preparatory work to support device flow authorizations

---

Source/OIDAuthState.h
Source/OIDAuthState.m
Source/OIDAuthorizationResponse.h
Source/OIDAuthorizationResponse.m
Source/OIDAuthorizationService.h
Source/OIDFieldMapping.h
Source/OIDFieldMapping.m
Source/OIDRegistrationRequest.h
Source/OIDRegistrationResponse.h
Source/OIDRegistrationResponse.m
Source/OIDServiceDiscovery.h
Source/OIDServiceDiscovery.m
Source/OIDTokenRequest.h
Source/OIDTokenResponse.h
Source/OIDTokenResponse.m
Source/iOS/OIDAuthorizationUICoordinatorIOS.h

Closes #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/79)

Fix conflicting nullability specifier warnings

---

Examples/Example-iOS_ObjC/Example.xcodeproj/project.pbxproj
Examples/Example-iOS_ObjC/Example.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Examples/Example-iOS_ObjC/Source/AppAuthExampleViewController.m
Examples/Example-iOS_ObjC/Tests/AppAuthExampleTests.m
Examples/Example-iOS_ObjC/Tests/Info.plist

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/83)

Added Test target to the iOS ObjC Example.

---

AppAuth.xcodeproj/project.pbxproj
Examples/Example-macOS/Example-macOS.xcodeproj/project.pbxproj
Examples/Example-macOS/Tests/AppAuthExampleTests.m
Examples/Example-macOS/Tests/Info.plist
Source/OIDAuthState.h

tvOS and macOS library test targets
macOS Example test target.

Added more test targets.

---

Examples/README-PingFederate.md
Examples/README.md

Create examples readme for PingFederate server

Create PingFederate Readme

---

Source/OIDAuthorizationRequest.m
Source/OIDError.h
Source/OIDError.m
UnitTests/OIDAuthorizationRequestTests.m

Addresses confusion raised in #88. 
#98 is the feature request for adding proper hybrid flow support (currently closed – but feel free to comment there).

Throws error on unsupported response type

---

Examples/README-Okta.md

Included instructions on getting the AppAuth library set up with the Okta OpenID Connect endpoints.

Added an Okta config walkthrough

---

.travis.yml

- Per: https://github.com/codecov/example-objc

Configured xcodebuild to generate coverage files for Codecov.

---

README.md

Updated static library instructions to use default AppAuth folder name.

---

Source/OIDAuthState.m

OIDAuthState serialization now includes the needsTokenRefresh property.

---

AppAuth.xcodeproj/project.pbxproj
Source/AppAuth.h
Source/OIDAuthorizationService.m
Source/OIDURLSessionProvider.h
Source/OIDURLSessionProvider.m
UnitTests/OIDURLSessionProviderTests.m

#137 Making NSURLSession extensible

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

The only change to the defaults is a question about iOS 12 (since we've gotten 4 or so issue requests about it by now).

Create issue templates for bugs and feature requests.

---

Source/OIDAuthorizationService.m

Increase ID Token acceptable `iat` clock skew to +/- 10min

---

Source/OIDAuthorizationService.m
Source/OIDDefines.h

Useful when debugging IdP issues.

Add request trace logging enabled via the preprocessor define

---

Source/OIDAuthorizationRequest.m
Source/OIDTokenUtilities.h
Source/OIDTokenUtilities.m

Trivial but it gave me pause for thought so probably worth fixing.
I've signed a CLA: https://openid.net/wordpress-content/uploads/2018/04/OIDF_CLA-Agreement-Individual_Joseph-Heenan_2018-03-30.pdf

Fix typo (sha265 -> sha256)

---

Source/iOS/OIDExternalUserAgentIOS.m

Always dismiss the ASWebAuthenticationSession when resuming

---

Source/iOS/OIDExternalUserAgentIOS.m

Fixes issue with Guided Access or Single App modes  (rdar://40809553)

---

AppAuth.podspec
Source/iOS/OIDExternalUserAgentIOS.m

Fixes #365 on pre-1 version.
@WilliamDenniss Could you please create a version 0.95.1?

Backporting "Fixes issue with Guided Access or Single App modes (rdar://40809553)" to pre-1 version

---

Source/OIDAuthorizationService.m

Fixes #341 in a more generic way

Make the issued at time skew a constant

---

Source/iOS/OIDExternalUserAgentIOS.m

Attempt to fix https://github.com/openid/AppAuth-iOS/issues/400

Fix iOS 13 compatibility issue

---

Source/OIDAuthorizationService.m

Consider any azp claim when validating aud.

---

AUTHORS
AppAuth.xcodeproj/project.pbxproj
Source/AppAuth.h
Source/Framework/AppAuth.h
Source/iOS/OIDAuthState+IOS.h
Source/iOS/OIDAuthState+IOS.m
Source/iOS/OIDAuthorizationService+IOS.m
Source/iOS/OIDExternalUserAgentCatalyst.h
Source/iOS/OIDExternalUserAgentCatalyst.m
Source/iOS/OIDExternalUserAgentIOS.h
Source/iOS/OIDExternalUserAgentIOS.m
Source/iOS/OIDExternalUserAgentIOSCustomBrowser.h
Source/iOS/OIDExternalUserAgentIOSCustomBrowser.m

Rebasing and squishing #455 for merging.

Rebase of PR455 (Mac Catalyst Support)

---

Examples/Example-tvOS/Example-tvOS.xcodeproj/project.pbxproj
Examples/Example-tvOS/Example-tvOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Examples/Example-tvOS/Example-tvOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Examples/Example-tvOS/Example-tvOS/AppAuthTVExampleViewController.h
Examples/Example-tvOS/Example-tvOS/AppAuthTVExampleViewController.m
Examples/Example-tvOS/Example-tvOS/AppDelegate.h
Examples/Example-tvOS/Example-tvOS/AppDelegate.m
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
Examples/Example-tvOS/Example-tvOS/Assets.xcassets/Contents.json
Examples/Example-tvOS/Example-tvOS/Base.lproj/LaunchScreen.storyboard
Examples/Example-tvOS/Example-tvOS/Info.plist
Examples/Example-tvOS/Example-tvOS/Main.storyboard
Examples/Example-tvOS/Example-tvOS/main.m
Examples/Example-tvOS/Podfile

Todo: Add README file
Future todo: Discovery?

Example-tvOS

---

Examples/Example-tvOS/README.md
Examples/README-Google.md
Examples/README.md
README.md

Still working on main README changes, included are the changes for the example project/Google IdP details.

README changes for AppAuthTV

---

Source/AppAuthCore/OIDServiceConfiguration.m

Move from OIDServiceDiscovery to NSURL

Fix up type in designated initializer

---

DESIGN.md

Originally drafted June 1, 2018.

Document the design principles behind AppAuth

---

Source/AppAuthCore/OIDServiceConfiguration.m

This PR is relate to the issue #479

Fix for Unarchive with unarchivedObjectOfClass:fromData:error:

---

AppAuth.podspec
CHANGELOG.md

Prepare patch release for v1.6.1

Update podspec version and added description to changelog

---

AppAuth.xcodeproj/project.pbxproj

Fixes https://github.com/openid/AppAuth-iOS/issues/765

Update framework minimum OS versions

---

AppAuth.podspec
CHANGELOG.md

Also add changes to CHANGELOG.
Release should resolve https://github.com/google/GoogleSignIn-iOS/issues/376

Prep for patch release fixing broken API change
