Doxyfile, Source/OIDAuthorizationRequest.h, Source/OIDAuthorizationRequest.m, UnitTests/OIDAuthorizationRequestTests.m
Previously we only allowed the `code_verifier` to be changed by the developer, but we had no way to change the `code_challenge` and `code_challenge_method` (aside from turning PKCE it off entirely by passing `nil` as the code verifier).
This patch enables all PKCE params to be modified, while retaining the opinionated S256 default.
=> Allow all PKCE parameters to be overwritten (not just the code verifier)

Source/OIDServiceDiscovery.m
Per Objective-C guidelines, error pointers may be set to nil/null if the caller doesn't care about specifics of the error. In this case, *error is a nil pointer dereference and will crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/26)
=> Fix nil pointer dereference when 'nil' passed in to receive error

Source/OIDAuthorizationRequest.h, Source/OIDAuthorizationRequest.m, Source/OIDServiceConfiguration.h, Source/OIDServiceConfiguration.m
This change removes `nullable` annotations from user-facing initializers which makes them much nicer to use at the Swift call-site:
_Before:_
```swift
let config = OIDServiceConfiguration(authorizationEndpoint: authEndpoint,
tokenEndpoint: tokenEndpoint)!
```
_After (no force-unwrapping required):_
```swift
let config = OIDServiceConfiguration(authorizationEndpoint: authEndpoint,
tokenEndpoint: tokenEndpoint)
```
I've checked the initializers if there is any chance they could ever return `nil` and it turned out there is none. They do call `NSObject`'s `init` which guarantees to never return `nil`.
There are many more initializers in this project marked as `nullable`, but these two classes are the most "visible" ones to library users.
---
This change is [<img …
=> Nonnull initializers

Source/OIDTokenRequest.m
Changing the OID_UNAVAILABLE_USE_INITIALIZER message from -[OIDTokenRequest init] to use the valid default init selector ("clientSecret:" was missing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/37)
=> Removing unknown selector warning OIDTokenRequest

Example-Mac/Source/AppAuthExampleViewController.m
Access token and id token can be nil when OIDAuthStateAction is called (when having an error). The definition of OIDAuthStateAction is correct, but the callback is wrongly defined in AppAuthExampleViewController.m.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/39)
=> Access token and id token can be nil when OIDAuthStateAction is called.

Source/OIDTokenRequest.m
If client_secret is present, it should be used on all token endpoint requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/43)
=> Fixed handling of client_secret for token endpoint requests.

AppAuth.podspec, AppAuth.xcodeproj/project.pbxproj, Example-Mac/Example-Mac.xcodeproj/project.pbxproj, Example-Mac/Source/AppAuthExampleViewController.h, Example-Mac/Source/AppAuthExampleViewController.m, Example-Mac/Source/Base.lproj/AppAuthExampleViewController.xib, Source/AppAuth.h, Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.h, Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.m, Source/macOS/OIDRedirectHTTPHandler.h, Source/macOS/OIDRedirectHTTPHandler.m
This PR adds the option to handle loopback IP HTTP redirects for macOS.  Loopback redirects are an alternative redirect choice to custom URI scheme based redirects on macOS. Both choices have their pros and cons, this gives developers the choice.
To enable this, I have introduced some third-party code (taken from an Apple sample), clearly marked as such, to provide the HTTP server functionality, modified to listen only on the loopback interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/42)
=> Loopback HTTP redirect support for macOS

AppAuth.podspec, AppAuth.xcodeproj/project.pbxproj, Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.h, Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.m
Notes:
– `HTTPConnection` objects were previously self-retaining. HTTPServer now keeps track of them instead so they are retained correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/51)
=> ARC-ified the loopback HTTP server class.

Example-Mac/Source/AppAuthExampleViewController.m, Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.h, Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.m, Source/macOS/OIDRedirectHTTPHandler.h, Source/macOS/OIDRedirectHTTPHandler.m
- Automatically closes the loopback HTTP server once an authorization response is received.
- Now cancels the previous request if OIDRedirectHTTPHandler::startHTTPListener is called more than once.
- Removed dead code in OIDLoopbackHTTPServer related to the default behavior when no delegate set to handle connections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/53)
=> Loopback HTTP server automatically shuts down following authorization.

Source/OIDAuthState.m, Source/OIDError.h, UnitTests/OIDAuthStateTests.m
Follow the same implementation details regarding refresh tokens as in the Android SDK, resulting from [this discussion](https://github.com/openid/AppAuth-Android/pull/42).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openid/appauth-ios/23)
=> Be more lenient about refresh tokens.

Source/iOS/OIDAuthorizationUICoordinatorIOS.h, Source/iOS/OIDAuthorizationUICoordinatorIOS.m
Adds SFSafariViewController customization to the library by introducing a new protocol; OIDSafariViewControllerFactory - which allows the library consumer to take control of the SFSafariViewController creation, if they want.
Instructions:
- Create a class which implements the @c OIDSafariViewControllerFactory protocol.
- Implement the @c OIDSafariViewControllerFactory.safariViewControllerWithURL: method.
- Create a new instance of your @c OIDSafariViewControllerFactory at application startup (or at any time before an interactive authorization is attempted.)
- Call: [OIDAuthorizationUICoordinatorIOS setSafariViewControllerFactory:myFactory];
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Adds SFSafariViewController customization.

Source/OIDAuthorizationService.m, Source/OIDErrorUtilities.m
I heard some reports that it was hard to diagnose issues in AppAuth. While testing #22 I noticed that they were fairly opaque.
I believe the issue is that `localizedDescription` will contain a default description if we don't set one.  We were setting a `localizedFailureReason`, but when the developer calls `localizedDescription` and they get a vague default error, they may not think to check `localizedFailureReason`.
This PR sets localizedDescription overriding the vague default, and leaves localizedFailureReason nil. In the future if we were to set localizedFailureReason, we should always ensure that localizedDescription is included to avoid this usability issue.
Also passed through the description for the non-OAuth errors (like network errors).
---
This change is [<img …
=> Sets the NSError localizedDescription in more cases.

Source/OIDTokenRequest.m, UnitTests/OIDAuthorizationRequestTests.h, UnitTests/OIDAuthorizationRequestTests.m, UnitTests/OIDAuthorizationResponseTests.h, UnitTests/OIDAuthorizationResponseTests.m, UnitTests/OIDTokenRequestTests.m
With this change, AppAuth will support no-client-auth (suitable for clients without a secret) and Basic client auth (suitable for clients with a secret).
Previously AppAuth supported no-client-auth, and client credentials in the request body.
Basic auth support is [required](https://tools.ietf.org/html/rfc6749#section-2.3.1) by OAuth 2.0, which also recommends against client credentials in the request body when the client is capable of doing Basic auth (which AppAuth is capable of).
Replaces #24, but doesn't offer the extensibility that #24 did.
=> Support for Basic Client Authentication

AppAuth.xcodeproj/project.pbxproj
Set `SKIP_INSTALL = YES` for AppAuth-macOS build configurations as referenced in this issue:  https://github.com/openid/AppAuth-iOS/issues/115
Submitted on behalf of Zetetic, LLC
=> Fix skip install for macOS

Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.h, Source/macOS/LoopbackHTTPServer/OIDLoopbackHTTPServer.m, Source/macOS/OIDRedirectHTTPHandler.m
We had a user with IPv6 completely disabled (on Mac), which was causing `-[HTTPServer start:]` to fail.
Since only the IPv4 loopback address is used, I've made `start:` succeed even if it can't bind an IPv6 socket.
I also added the option of using the IPv6 loopback address (`::1`) in the future if iPv6 should be preferred over IPv4.
=> -[HTTPServer start:] will no longer fail if it can't bind an IPv6 socket

Source/OIDAuthorizationRequest.m, Source/OIDError.h, Source/OIDError.m
This is a fix for Issue #105 
Summarizing Findings:
- Root cause is in GTMAppAuth.
- Which is synthesizing an OIDTokenRequest with grant type "token" when it should be "refresh_token".
- And which is synthesizing an OIDAuthorizationRequest with response type "token" when it should be "code".
- Fixing root cause is a necessary, but not a sufficient, fix for this problem.
- Existing clients have incorrect OIDAuthorizationRequest instances stored in their keychains as a result of the root cause issue.
- Apps which upgraded to a version of AppAuth-iOS after March 25th when PR #99 was merged into master, who had clients with GTMOAuth2Touch, will be experiencing crashes for the reasons reported in this issue.
- GTMAppAuth will be fixed in a separate issue.
- A workaround will be applied here. …
=> Fix for Issue #105

.travis.yml
Travis uses xctool by default to build and test the project, but
this is currently broken for xcode 9:
https://github.com/facebook/xctool/issues/738
Switch to xcodebuild for now.
=> xctool build is broken; use xcodebuild

Source/OIDAuthorizationResponse.m
Section 4.1.3 of RFC 6749 does not document scope as an allowed parameter.
Fix for #156.
=> Removed `scope` from authorization code exchange token request.

.travis.yml, AppAuth.podspec, Source/OIDURLQueryComponent.m, Source/iOS/OIDAuthorizationUICoordinatorIOS.m
Implemented dismiss functionality for SFAuthenticationSession on iOS 11.
Removed GCC_TREAT_WARNINGS_AS_ERRORS=YES from the Podspec, enabled `-Werror` for TravisCI instead to catch new warnings at the library-developer level.
AppAuth now requires a Base SDK of iOS 11 (still supports iOS 7 as a Deployment Target).
Fixes #146
=> Resolved the "-Wpartial-availability" warning.

AppAuth.podspec, AppAuth.xcodeproj/project.pbxproj, Source/OIDURLQueryComponent.m
– iOS deployment target is 7.0 for the static lib, and 8.0 for the Framework (the static lib had been set to 8.0 incorrectly).
– macOS deployment target is 10.9 (was on 10.8, but wouldn't have worked).
– Added proper availability flags to OIDURLQueryComponent for macOS.
=> Fixed deployment targets and availability.

AppAuth.xcodeproj/project.pbxproj
- Both Release and Debug were being built with -fembed-bitcode-marker
which doesn't actually embed bitcode.
- Now -fembed-bitcode is passed which should embed the bitcode correctly.
Should fix https://github.com/google/google-api-objectivec-client-for-rest/issues/171
=> Set BITCODE_GENERATION_MODE to 'bitcode'

AppAuth.xcodeproj/project.pbxproj
Fixes bug in #169, new class was only added to the iOS targets.
=> Added OIDURLSessionProvider to missing targets.

Examples/Example-iOS_Swift-Carthage/.gitignore, Examples/Example-iOS_Swift-Carthage/Cartfile, Examples/Example-iOS_Swift-Carthage/Cartfile.resolved, Examples/Example-iOS_Swift-Carthage/Example.xcodeproj/project.pbxproj, Examples/Example-iOS_Swift-Carthage/Example.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Examples/Example-iOS_Swift-Carthage/Source/AppAuthExampleViewController.swift, Examples/Example-iOS_Swift-Carthage/Source/AppDelegate.swift, Examples/Example-iOS_Swift-Carthage/Source/Assets.xcassets/AppIcon.appiconset/Contents.json, Examples/Example-iOS_Swift-Carthage/Source/Base.lproj/LaunchScreen.storyboard, Examples/Example-iOS_Swift-Carthage/Source/Base.lproj/Main.storyboard, Examples/Example-iOS_Swift-Carthage/Source/Info.plist
Added iOS example app using Swift
Notes:
Example app supports iOS 9+
App differs in UI and code separations from Obj-C example. 
AppAuth workflow is same as other example apps.
=> Added iOS example app using Swift

Source/OIDAuthorizationService.m
In case of “state” parameter mismatch between request and response, the
generated error was not populated with the right information. Also, the
OAuth 2 response is “valid” regardless of the state parameter so it
makes sense to create the response object before checking for the state
parameter.
=> State parameter mismatch

AppAuth.xcodeproj/project.pbxproj, Source/AppAuth.h, Source/Framework/AppAuth.h, Source/OIDEndSessionRequest.h, Source/OIDEndSessionRequest.m, Source/OIDEndSessionResponse.h, Source/OIDEndSessionResponse.m, Source/OIDServiceDiscovery.h, Source/OIDServiceDiscovery.m, UnitTests/OIDEndSessionRequestTests.h, UnitTests/OIDEndSessionRequestTests.m, UnitTests/OIDServiceDiscoveryTests.m
From @zachmargolis:
>These are the basic objects needed to support RP-initiated logout, I'd like to make sure they look ship-shape before adding methods to use them and follow up in another PR
I've picked his work, and fixed the comments made by @WilliamDenniss
=> Picking up on @zachmargolis work, and fixing review comments

AppAuth.xcodeproj/project.pbxproj, Source/AppAuth.h, Source/Framework/AppAuth.h, Source/OIDURLQueryComponent.h, Source/OIDURLQueryComponent.m, Source/iOS/OIDAuthorizationUICoordinatorCustomBrowser.h, Source/iOS/OIDAuthorizationUICoordinatorCustomBrowser.m
- An UICoordinator for iOS to support auth with a custom iOS browser like Chrome or Firefox.
- Implements #200.
=> Add custom browser support

AppAuth.xcodeproj/project.pbxproj, Source/AppAuth.h, Source/Framework/AppAuth.h, Source/OIDAuthState.m, Source/OIDAuthorizationRequest.h, Source/OIDAuthorizationRequest.m, Source/OIDAuthorizationService.h, Source/OIDAuthorizationService.m, Source/OIDError.h, Source/OIDIDToken.h, Source/OIDIDToken.m, Source/OIDServiceConfiguration.h, Source/OIDServiceConfiguration.m, Source/OIDTokenResponse.h, UnitTests/OIDAuthorizationRequestTests.m, UnitTests/OIDRPProfileCode.h, UnitTests/OIDRPProfileCode.m
* The 5 required fields are exposed as params.
* Authorization code exchange exchange now validates the ID Token iss, aud, and iat claims.
*AppAuth for iOS & macOS only supports `alg:none` validation.
#4  Support "nonce" OpenID Connect auth request parameter.
#17 Support JWT decoding and validation (conditional: alg:none based validation only).
#102 OpenID Connect RP Conformance Testing.
=> ID Token parsing and OpenID RP Certification

AppAuth.podspec, Source/iOS/OIDExternalUserAgentIOS.m
SFAuthenticationSession is deprecated. Uses the replacement (and functionally equivalent) ASWebAuthenticationSession on iOS 12+.
AuthenticationServices framework is now required.
As with #129:
– CI will likely fail
– On Approval, PR will be merged in to a branch named `iOS12beta`, not `master`.
– When iOS 12 and Xcode 10 go GA, the `__IPHONE_OS_VERSION_MAX_ALLOWED` gating will be removed (as AppAuth only supports the latest Xcode), and the feature will be merged into `master`.
The platform beta version of AppAuth *should* work just fine in Xcode 9 (without the iOS 12 functionality), though production use is not recommended.
=> Support iOS 12 Beta

Source/OIDAuthorizationService.m
401 is expected per RFC 6749 Section 5.2 for the invalid_client code.
Extensions to OAuth may use other error codes (presumably still in the 4xx range).
Fixes #234
=> Add support for 4xx errors

AppAuth.xcodeproj/project.pbxproj, Source/Framework/AppAuth.h
Hello @WilliamDenniss , long time no see 🙂 
I was using the AppAuth framework, when I encountered a situation where I needed to provide an URLSessionDelegate for authentication, and I couldn't seem to access OIDURLSessionProvider from Swift when integrating via Carthage.  Looking at the project in Xcode I noticed that the source files weren't added to the target, nor set to be publicly accessible.  I changed the settings as shown in the image below, and that fixed the issue:
OIDURLSessionProvider.h
OIDURLSessionProvider.m
I did notice the earlier PR which promises to fix the problem, so I'm wondering if maybe I've done something wrong?  At any rate, I really need this feature so I've made these changes locally and they work for me.  Hopefully it makes sense and is useful to you.  It would …
=> Expose OIDURLSessionProvider to framework

Source/OIDAuthorizationService.m, Source/OIDServiceDiscovery.m, Source/iOS/OIDExternalUserAgentIOS.m
=> Add a description to errors, even if they have an underlyingError with a description

Source/OIDAuthState.m, Source/OIDError.h, Source/OIDError.m, Source/OIDTokenRequest.h, Source/OIDTokenRequest.m, UnitTests/OIDTokenRequestTests.m
On close inspection of [RFC 6749 Section 6](https://tools.ietf.org/html/rfc6749#section-6), the `redirect_uri` isn't required and may cause issues on servers that are not expecting it.
Fixes #207
=> Remove the redirect_uri parameter from token refresh

AppAuth.xcodeproj/project.pbxproj
This project seems to use an indent width of 2; it makes life easier
for people that have to work on other projects with other indent widths
if that is specified in the xcodeproj.
=> Specify indent width in .xcodeproj

Source/OIDAuthState.h, Source/OIDAuthState.m, Source/OIDAuthorizationRequest.m, Source/iOS/OIDAuthState+IOS.h, Source/macOS/OIDAuthState+Mac.h, UnitTests/OIDAuthorizationRequestTests.m
This response type is required to build a FAPI compliant client, and as
the application can verify the id_token signature and c_hash before
calling the token endpoint there is no reason to block applications from
using code id_token.
Other response types are still blocked as they don't appear to make sense
in the context of a native app.
closes #292
=> Allow applications to use the "code id_token" response_type

Source/OIDRegistrationRequest.h, Source/OIDRegistrationRequest.m, UnitTests/OIDRegistrationRequestTests.m
As per the dynamic client registration specification, the AS may require an access token for access to the registration endpoint - allow the app to specify this.
(I've tried my best to follow the coding standard doc but it's quite long so very possible I missed something, let me know if so.)
=> Add support for an initial access token to registration endpoint

README.md
The minimum versions used in the Xcodeproj and the podspec are 10.9,
but README.md was stating 10.8 - updated it to 10.9 to match the other
references.
=> Correct supported macOS version in README.md

Source/OIDAuthState.m
Scope is a valid parameter for the Refresh Token request (Sectiom 6 of RFC
6749), however it's optional and when ommitted is treated as equal to the scope
originally granted by the resource owner. Since the indented behavior of this
convenience method is to create a token refresh with the full scope, it's
redundant to include.
Related to b5870c0bc6f65cb4004d697722612cd4a1019ab8 but slightly different
reason.
=> Remove `scope` from the token refresh request as it is redundant

Source/OIDAuthorizationService.m
Addressed an issue pointed out in [WIP](https://github.com/openid/AppAuth-iOS/pull/259#issuecomment-409830558) by @Amnell
=> Fixed an end session callback

.gitignore, AppAuth.podspec, AppAuth.xcodeproj/project.pbxproj, AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuthCore.xcscheme, CONTRIBUTORS, Source/AppAuth.h, Source/AppAuthCore.h, Source/CoreFramework/AppAuthCore.h, Source/CoreFramework/Info.plist, Source/Framework/AppAuth.h
New attempt, creates a separate include header file (AppAuthCore.h) for the subpsec and Framework targets, rather than attempting to use a single header with pre-processor defines.
This version passes `pod spec lint`, though in the 1.5.x release of CocoaPods there is an unrelated error (#7708) which is a KI. Linting with 1.6.0.beta.2 works, and the 1.5 version of CocoaPods can still be used with the library.
=> Create an AppAuth Core subspec & Framework target

Source/iOS/OIDExternalUserAgentIOS.h, Source/iOS/OIDExternalUserAgentIOS.m
Simplifying OIDExternalUserAgentIOS by removing customization that is only
relevant in old versions of iOS that may confuse developers starting on
iOS 12+.
AppAuth's pluggable `OIDExternalUserAgent` system can be used by users
who need customizations, e.g. by copying OIDExternalUserAgentIOS and
modifying as needed (no fork required).
=> Remove the setSafariViewControllerFactory API

Source/iOS/OIDExternalUserAgentIOS.h
Removed in 1.0. See https://github.com/openid/AppAuth-iOS/pull/326
=> Deprecate setSafariViewControllerFactory

AppAuth.podspec
Fixes #350 
Strongly linking the `AuthenticationServices` framework causes a dyld crash during startup on iOS 11 and older. This change weakly links the framework instead.
=> Weakly link AuthenticationServices framework

Source/macOS/OIDRedirectHTTPHandler.h, Source/macOS/OIDRedirectHTTPHandler.m
Some OAuth applications such as Reddit require that a redirect URI be specified at app setup time. This URI does not always support wildcard characters. The dynamic port binding in `- (NSURL *)startHTTPListener:(NSError **)returnError` then prevents the OAuth from completing successfully. 
This pull request adds an optional port parameter to this method which forces the port to whatever the developer wants while maintaining compatibility with the existing method.
=> Add the ability to dictate ports

Source/iOS/OIDAuthState+IOS.h, Source/iOS/OIDAuthState+IOS.m, Source/iOS/OIDExternalUserAgentIOS.h, Source/iOS/OIDExternalUserAgentIOS.m
This PR is referring to #338, iOS 11+ devices don't need to pass UIViewController in order to present an external user agent. 
```objc
// builds authentication request for apps that support iOS 11+
OIDAuthorizationRequest *request =
[[OIDAuthorizationRequest alloc] initWithConfiguration:configuration
clientId:kClientID
scopes:@[OIDScopeOpenID,
OIDScopeProfile]
redirectURL:KRedirectURI
responseType:OIDResponseTypeCode
additionalParameters:nil];
// performs authentication request
AppDelegate *appDelegate =
(AppDelegate *)[UIApplication sharedApplication].delegate;
appDelegate.currentAuthorizationFlow =
[OIDAuthState authStateByPresentingAuthorizationRequest:request
callback:^(OIDAuthState *_Nullable authState,
NSError *_Nullable error) {
if (authState) {
NSLog(@"Got authorization tokens. …
```
=> Present ExternalUserAgent without passing UIViewController for iOS 11+

Source/OIDServiceDiscovery.m, UnitTests/OIDServiceDiscoveryTests.m
Should catch the issue in #315 a little sooner.
=> Error when the JSON object isn't a NSDictionary

AppAuth.xcodeproj/project.pbxproj, Source/AppAuth.h, Source/Framework/AppAuth.h, Source/OIDAuthorizationService.h, Source/OIDAuthorizationService.m, Source/OIDEndSessionRequest.h, Source/OIDEndSessionRequest.m, Source/OIDEndSessionResponse.h, Source/OIDEndSessionResponse.m, Source/OIDServiceConfiguration.h, Source/OIDServiceConfiguration.m, Source/OIDServiceDiscovery.h, Source/OIDServiceDiscovery.m, UnitTests/OIDEndSessionRequestTests.h, UnitTests/OIDEndSessionRequestTests.m, UnitTests/OIDServiceDiscoveryTests.m
http://openid.net/specs/openid-connect-session-1_0.html#RPLogout
Implements #132. Fixes #258.
=> Implement OIDC RP-Initiated Logout

Source/OIDAuthorizationService.m
This fixes the [build error](https://travis-ci.org/openid/AppAuth-iOS/builds/543991588?utm_source=github_status&utm_medium=notification) on master.
=> Implement missing cancelWithCompletion: in OIDEndSessionImplementation

Source/iOS/OIDAuthState+IOS.h, Source/iOS/OIDExternalUserAgentIOS.h, Source/iOS/OIDExternalUserAgentIOS.m
Replaces use of the deprecated UIApplication.keyWindow. Alternative implementation of #428 
Undoes some changes made in #340
- Presenting UIViewController is required again for all versions of iOS
- Reversed deprecation of methods
Added assertion for iOS 13 to ensure the UIViewController is nonnull as required.
=> Use the UIViewController's window as the presenting anchor

Source/AppAuthCore.h, Source/CoreFramework/AppAuthCore.h
`OIDEndSessionRequest` and `OIDEndSessionResponse` were missing when importing AppAuthCore framework with Carthage.
=> import missing headers for OIDC logout in AppAuthCore.h

AppAuth.podspec
- Make the ExternalUserAgent depend on the Core subspec
- Make the ExternalUserAgent the default subspec
(This is in preparation for an EnterpriseUserAgent subspec which would in turn depend on ExternalUserAgent)
=> Make ExternalUserAgent default subspec and depend on Core subspec

Source/AppAuthEnterpriseUserAgent/iOS/OIDExternalUserAgentIOSCustomBrowser.m
Addresses https://github.com/openid/AppAuth-iOS/issues/506 by removing the use of "itms-apps".
OIDExternalAgentIOSCustomBrowser opens the App Store to install custom browsers if not installed, using the URI itms-apps://. This was replaced by https://, which was tested to instantly launch the App Store in iOS 13. Upon research this behavior may go back as far as iOS 6. In the worst case, https:// would cause a redirect to the browser followed by a redirect to the App Store.
=> Replace itms-apps with https in OIDExternalAgentIOSCustomBrowser

Examples/Example-iOS_ObjC-Carthage/Example.xcodeproj/project.pbxproj, Examples/Example-iOS_ObjC-Carthage/Example.xcodeproj/xcshareddata/xcschemes/Example_Extension.xcscheme, Examples/Example-iOS_ObjC-Carthage/Example_Extension/Base.lproj/MainInterface.storyboard, Examples/Example-iOS_ObjC-Carthage/Example_Extension/Example_Extension.entitlements, Examples/Example-iOS_ObjC-Carthage/Example_Extension/Info.plist, Examples/Example-iOS_ObjC-Carthage/Example_Extension/TodayViewController.h, Examples/Example-iOS_ObjC-Carthage/Example_Extension/TodayViewController.m, Examples/Example-iOS_ObjC-Carthage/Source/AppAuthExampleViewController.m, Examples/Example-iOS_ObjC-Carthage/Source/Example.entitlements, Examples/Example-iOS_ObjC/Example-iOS_ObjC.xcodeproj/project.pbxproj, Examples/Example-iOS_ObjC/Example-iOS_ObjC.xcodeproj/xcshareddata/xcschemes/Example-iOS_ObjC_Extension.xcscheme, Examples/Example-iOS_ObjC/Example-iOS_ObjC_Extension/Base.lproj/MainInterface.storyboard, Examples/Example-iOS_ObjC/Example-iOS_ObjC_Extension/Example-iOS_ObjC_Extension.entitlements, Examples/Example-iOS_ObjC/Example-iOS_ObjC_Extension/Info.plist, Examples/Example-iOS_ObjC/Example-iOS_ObjC_Extension/TodayViewController.h, Examples/Example-iOS_ObjC/Example-iOS_ObjC_Extension/TodayViewController.m, Examples/Example-iOS_ObjC/Podfile, Examples/Example-iOS_ObjC/Source/AppAuthExampleViewController.m, Examples/Example-iOS_ObjC/Source/Example-iOS_ObjC.entitlements, Examples/Example-iOS_Swift-Carthage/Example.xcodeproj/project.pbxproj, Examples/Example-iOS_Swift-Carthage/Example.xcodeproj/xcshareddata/xcschemes/Example.xcscheme, Examples/Example-iOS_Swift-Carthage/Example.xcodeproj/xcshareddata/xcschemes/Example_Extension.xcscheme, Examples/Example-iOS_Swift-Carthage/Example_Extension/Base.lproj/MainInterface.storyboard, Examples/Example-iOS_Swift-Carthage/Example_Extension/Example_Extension.entitlements, Examples/Example-iOS_Swift-Carthage/Example_Extension/Info.plist, Examples/Example-iOS_Swift-Carthage/Example_Extension/TodayViewController.swift, Examples/Example-iOS_Swift-Carthage/Source/AppAuthExampleViewController.swift, Examples/Example-iOS_Swift-Carthage/Source/Example.entitlements
This pull request adds extensions to all iOS examples by using the Core subspec (cocoapods) or Core framework (Carthage).
The extension is a simple UI with a logging view just like the app and allows to get the user profile.
I also discovered that the carthage example's extension is, surprisingly, able to build by importing the `AppAuth.framework` in contrary to the cocoapods example that is not building (it's the reason why the Core subspec exists). But importing `AppAuthCore.framework` instead fixes a linking warning.
=> Examples with extensions

AppAuth.xcodeproj/project.pbxproj
AppleTV test file was included in a source target which did not have XCTest dependencies and was causing builds to fail.
=> Remove OIDTVTokenRequestTests from sources for AppAuth-iOS scheme.

Source/AppAuthCore/OIDServiceDiscovery.h
Initially referred to a non-existent serviceDiscoveryWithURL:callback: method.
=> Update init unavailable doc on OIDServiceDiscovery

UnitTests/AppAuthTV/OIDTVAuthorizationResponseTests.m
There seems to be a hanging diagnostic pop that has no push which is causing Travis to fail.
It's been in this file throughout the history of the repo with no matching push so I deleted it.
=> Remove unmatched diagnostic pop

Package.swift
=> Set min iOS version to 9 for SPM

Source/AppAuthCore/OIDServiceConfiguration.m, Source/AppAuthCore/OIDServiceDiscovery.m, UnitTests/OIDServiceDiscoveryTests.m
Provide our own implementation of `NSCoding` for `OIDServiceDiscovery` rather than delegating to `NSDictionary` and maintain support for decoding the old encoding for backward compatibility.  Ensure that OIDServiceConfiguration can successfully decode the old encoding when `requiresSecureCoding` is enabled.  Test both new and old encodings with `requiresSecureCoding` enabled.
=> Correct OIDServiceDiscovery's NSCoding implementation

.github/workflows/tests.yml
Use the [macos-11 runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) until we're ready to switch to macos-12.
=> Use the macos-11 runner

AppAuth.podspec, Package.swift
Fixes https://github.com/openid/AppAuth-iOS/issues/759
=> Bump iOS minimum version in podspec to support Xcode 14.3

Source/AppAuth/iOS/OIDExternalUserAgentIOS.h, Source/AppAuth/iOS/OIDExternalUserAgentIOS.m
This PR fixes this build warning:
> Source/AppAuth/iOS/OIDExternalUserAgentIOS.h:37:1: warning build: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
Unfortunately, this warning is misleading. `-[NSObject init]` doesn't have any nullability annotation, which is equivalent to `null_unspecified`, but `-[OIDExternalUserAgentIOS init]` has the conflicting `nullable` annotation.
The straightforward solution would be to remove the annotation here to get in sync with the base class, but this would be incorrect: In line 34, `NS_ASSUME_NONNULL_BEGIN` is used, which would make the annotation default to `nonnull` instead of `null_unspecified`, which is why `null_unspecified` has to be used explicitly.
To verify the fix, run the iOS tests in …
=> Fix nullability annotation for -[OIDExternalUserAgentIOS init]

Source/AppAuthCore/OIDAuthorizationRequest.h, Source/AppAuthCore/OIDAuthorizationRequest.m, UnitTests/OIDAuthorizationRequestTests.m
this PR is in response to this PR which has been opened ~ year ago and appears to be in a limbo
https://github.com/google/GoogleSignIn-iOS/pull/244
The PR did get a review from @mdmathias who pointed out one issue [here](https://github.com/google/GoogleSignIn-iOS/pull/244#discussion_r1213748728) that seems to prevent the PR from getting merged. 
There is a substantial community interest to get the PR merged and it appears there is willingness on the google side as well.
I'm attempting to unblock the PR by adding the initializer that is being asked for in the review comment (linked above).
Thank you in advance for your review
=> feat: allow custom nonce in OIDAuthorizationRequest

Source/AppAuthCore/OIDTokenRequest.m, UnitTests/OIDTokenRequestTests.m
This update fixes wrong variable copy-pasted code for additional http headers in OIDTokenRequest.
=> fixed wrong variable for additional http headers in OIDTokenRequest (#770)

AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth-iOS.xcscheme, AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth-tvOS.xcscheme, Source/AppAuthCore/OIDAuthorizationResponse.h, Source/AppAuthCore/OIDAuthorizationResponse.m
AppAuth release 1.7.0 inadvertently removed a method from the public interface of `OIDAuthorizationResponse`. This PR adds the method back.
This fix and subsequent release should fix https://github.com/google/GoogleSignIn-iOS/issues/376.
=> Add back missing method to OIDAuthorizationResponse

AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth-macOS.xcscheme, Source/AppAuthCore/OIDTokenRequest.h, Source/AppAuthCore/OIDTokenRequest.m, Source/AppAuthTV/OIDTVTokenRequest.h, Source/AppAuthTV/OIDTVTokenRequest.m
Fixes additional method name changes in #770 impacting https://github.com/google/GoogleSignIn-iOS/issues/376
I tested these changes against the [DaysUntilBirthday sample app in Google Sign-In iOS](https://github.com/google/GoogleSignIn-iOS/tree/main/Samples/Swift/DaysUntilBirthday). That sample built and ran without issue.
=> Fix OIDTokenRequest for AppAuthCore and AppAuthTV

AppAuth.podspec, PrivacyInfo.xcprivacy
Also removes empty dictionaries from PrivacyInfo.xcprivacy file that seemed to cause errors in the archived product's privacy report.
Fixes #829
=> Streamline copying of privacy manifest

AppAuth.podspec
=> Adds defines module to AppAuth.podspec

AppAuth.podspec
Updates `AppAuth.podspec` to use the correct xcconfig syntax per the [CocoaPods documentation](https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig).
Fixes #850
=> Use correct xcconfig syntax for podspec

Sources/AppAuth/iOS/OIDExternalUserAgentIOSCustomBrowser.m
[`UIApplication openURL:`](
https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl?language=objc) is deprecated and has no effect.
On iOS 10.0+, [`UIApplication openURL:options:completionHandler:`](https://developer.apple.com/documentation/uikit/uiapplication/1648685-openurl?language=objc) should be used instead.
I am contributing on behalf of Google, which has a CLA with the OpenID Foundation.
Relevant issue: https://github.com/openid/AppAuth-iOS/issues/703
=> Fix OIDExternalUserAgentIOSCustomBrowser on iOS 10+

AppAuth.podspec, AppAuth.xcodeproj/project.pbxproj, CONTRIBUTORS, Package.swift, README.md, Sources/AppAuth/iOS/OIDExternalUserAgentIOS.m, Sources/AppAuth/iOS/OIDExternalUserAgentIOSCustomBrowser.m
When you compile with Xcode 16, [UIApplication openURL:] no longer functions and just returns NO. As Apple is going to require compilation with Xcode 16 in 2025-04, lets expunge it from the code.
This requires moving the iOS minimum up to iOS 10.
=> Remove [UIApplication openURL:]
